apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-action-deployment
  namespace: webapps
  labels:
    tier: webapp
    name: github-action
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: webapp
      name: github-action
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        tier: webapp
        name: github-action
    spec:
      containers:
      - name: github-action-kiranprav
        imagePullPolicy: Always
        image: "358308582535.dkr.ecr.ap-south-1.amazonaws.com/kiranprav:latest"
        ports:
        - containerPort: 8080
 ---
apiVersion: v1
kind: Service
metadata:
  name: github-action-service
  namespace: webapps
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: github-action
