name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: test

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package --file spring-boot-app/pom.xml

      - name: Trivy FS Scan
        run: |
          trivy fs --format table -o trivy-fs-report.html .

      - name: Build Docker Image
        run: |
          docker build -t kiran/abhishek:latest -f spring-boot-app/Dockerfile spring-boot-app/

      - name: Trivy Image Scan
        run: |
          trivy image --format table -o trivy-image-report.html kiran/abhishek:latest
